kafka:
  bootstrap-servers: localhost:9092
  topic:
    signal: nodered
    sensor: test
server:
  port: 9002
  
spring :
   datasource:
         url: jdbc:mysql://localhost:3306/meta_data_handler?verifyServerCertificate=false&useSSL=false
         username: root
         password: root   
         
   jpa:
     hibernate:
          ddl-auto: update 
   
  



